CREATE TABLE tipo_arquivo
(
    id_tipo_arquivo BIGINT AUTO_INCREMENT PRIMARY KEY,
    descricao       VARCHAR(255) NOT NULL,
    is_active       TINYINT DEFAULT 1
);

INSERT INTO tipo_arquivo (descricao)
VALUES ('Exame de Sangue'),
       ('Exame de Imagem'),
       ('Bioimpedância'),
       ('Receita Médica'),
       ('Laudo Médico'),
       ('Exame de Urina'),
       ('Eletrocardiograma'),
       ('Ultrassonografia'),
       ('Ressonância Magnética'),
       ('Tomografia Computadorizada'),
       ('Atestado Médico'),
       ('Exame de Vista'),
       ('Audiometria'),
       ('Teste de Glicemia'),
       ('Exame de Fezes'),
       ('Biopsia'),
       ('Exame Dermatológico'),
       ('Mapa de Pressão Arterial'),
       ('Holter 24 Horas'),
       ('Exame de Espirometria'),
       ('Teste de Esforço'),
       ('Angiografia'),
       ('Cintilografia'),
       ('Colonoscopia'),
       ('Endoscopia'),
       ('Teste Ergométrico'),
       ('Exame de Pele'),
       ('Exame Oftalmológico'),
       ('Prescrição de Óculos'),
       ('Relatório de Cirurgia'),
       ('Exame Psiquiátrico'),
       ('Avaliação Nutricional'),
       ('Exame de Densitometria Óssea'),
       ('Exame de PCR'),
       ('Radiografia'),
       ('Teste de Hepatite'),
       ('Teste de HIV'),
       ('Cultura Bacteriana'),
       ('Exame de Eletroneuromiografia'),
       ('Teste de Gravidez'),
       ('Ultrassonografia Obstétrica'),
       ('Teste de Estreptococo'),
       ('Exame de Tireoide'),
       ('Papanicolau'),
       ('Mamografia'),
       ('Teste de Fertilidade'),
       ('Exame de Colesterol'),
       ('Vacinação'),
       ('Registro de Consulta'),
       ('Exame de Doppler'),
       ('Certificado de Vacinação'),
       ('Exame de Sangue Oculto'),
       ('Exame Genético'),
       ('Teste de Alergia'),
       ('Registro de Internação'),
       ('Prontuário Médico'),
       ('Exame de Varizes'),
       ('Exame de Cateterismo'),
       ('Teste de Função Pulmonar'),
       ('Exame de Análise de Marcha'),
       ('Registro de Alta Médica'),
       ('Consulta de Seguimento'),
       ('Consulta de Urgência'),
       ('Relatório de Fisioterapia'),
       ('Avaliação Psicológica'),
       ('Teste Cutâneo'),
       ('Registro de Anestesia'),
       ('Exame de Artroscopia'),
       ('Exame de Litotripsia'),
       ('Avaliação de Risco Cirúrgico'),
       ('Exame de Mielografia'),
       ('Exame de Pet Scan'),
       ('Teste de Flexibilidade'),
       ('Exame de Capacidade Respiratória'),
       ('Registro de Transplante'),
       ('Exame de Biometria'),
       ('Exame de Gastroscopia'),
       ('Avaliação Otorrinolaringológica'),
       ('Exame de Peniscopia'),
       ('Registro de Quimioterapia'),
       ('Exame de Retossigmoidoscopia'),
       ('Exame de Uretrocistografia'),
       ('Exame de Videolaringoscopia'),
       ('Teste de Snellen (Visão)'),
       ('Exame de Escleroterapia'),
       ('Teste de Estresse Oxidativo'),
       ('Registro de Radioterapia'),
       ('Exame de Cromatografia'),
       ('Exame de Espectrometria'),
       ('Registro de Hemodiálise'),
       ('Exame de Eletrorretinografia'),
       ('Teste de Marcha de 6 Minutos'),
       ('Exame de Urodinâmica'),
       ('Teste de Schirmer (Olho Seco)'),
       ('Exame de Tonometria (Pressão Ocular)'),
       ('Avaliação de Equilíbrio'),
       ('Exame de Impedanciometria (Ouvido)'),
       ('Avaliação de Dor Crônica'),
       ('Teste de Sudorese'),
       ('Exame de Potencial Evocado');

