CREATE TABLE fabricante_medicamento
(
    id_fabricante_medicamento BIGINT AUTO_INCREMENT PRIMARY KEY,
    descricao                 VARCHAR(255) NOT NULL,
    criado_em                 DATETIME,
    criado_por_id             BIGINT,
    alterado_em               DATETIME,
    alterado_por_id           BIGINT,
    is_active                 TINYINT DEFAULT 1
);


INSERT INTO fabricante_medicamento (descricao, is_active)
VALUES ('Pfizer', 1),
       ('Johnson & Johnson', 1),
       ('Eurofarma', 1),
       ('Aché', 1),
       ('EMS', 1),
       ('Cristália', 1),
       ('Hypera Pharma', 1),
       ('Biolab Sanus Farmacêutica', 1),
       ('Blau Farmacêutica', 1),
       ('Libbs Farmacêutica', 1),
       ('União Química', 1),
       ('Germed Farmacêutica', 1),
       ('Grupo NC', 1),
       ('Farmoquímica', 1),
       ('Greenpharma Química e Farmacêutica', 1),
       ('Herbarium', 1),
       ('Natura', 1),
       ('Boticário', 1),
       ('Raia Drogasil', 1),
       ('Pague Menos', 1),
       ('Panvel Farmácias', 1),
       ('Profarma Distribuidora', 1),
       ('Novartis', 1),
       ('Roche', 1),
       ('Merck & Co.', 1),
       ('Sanofi', 1),
       ('GlaxoSmithKline', 1),
       ('AstraZeneca', 1),
       ('AbbVie', 1),
       ('Bayer', 1),
       ('Eli Lilly and Company', 1),
       ('Bristol-Myers Squibb', 1),
       ('Gilead Sciences', 1),
       ('Amgen', 1),
       ('Teva Pharmaceutical Industries', 1),
       ('Takeda Pharmaceutical Company', 1),
       ('Novo Nordisk', 1),
       ('Boehringer Ingelheim', 1),
       ('Baxter International', 1),
       ('Regeneron Pharmaceuticals', 1),
       ('Biogen', 1),
       ('Celgene Corporation', 1),
       ('Merck KGaA', 1),
       ('Mylan N.V.', 1),
       ('CSL Limited', 1),
       ('Allergan', 1),
       ('Genentech', 1),
       ('Otsuka Pharmaceutical', 1),
       ('Stada Arzneimittel', 1),
       ('Daiichi Sankyo', 1),
       ('Sandoz', 1),
       ('Lundbeck', 1),
       ('Alcon', 1),
       ('Cipla', 1),
       ('Sun Pharmaceutical Industries', 1),
       ('Dr. Reddy’s Laboratories', 1),
       ('Aspen Pharmacare', 1),
       ('Vertex Pharmaceuticals', 1),
       ('Ipsen', 1),
       ('Fresenius', 1),
       ('Nova Química', 1),
       ('Torrent Pharma', 1),
       ('Pfizer Brasil', 1),
       ('Sanofi Brasil', 1),
       ('Novartis Brasil', 1),
       ('Bayer Brasil', 1),
       ('Roche Brasil', 1),
       ('Abbott Brasil', 1),
       ('Boehringer Ingelheim Brasil', 1),
       ('AstraZeneca Brasil', 1),
       ('Merck Brasil', 1),
       ('Janssen-Cilag', 1),
       ('Teva Brasil', 1),
       ('GSK Brasil', 1),
       ('Lilly Brasil', 1),
       ('Sandoz Brasil', 1),
       ('Allergan Brasil', 1),
       ('Takeda Brasil', 1),
       ('Bristol-Myers Squibb Brasil', 1),
       ('Amgen Brasil', 1);
