CREATE TABLE formulario_alimentar
(
    id_formulario_alimentar BIGINT AUTO_INCREMENT PRIMARY KEY,
    id_consulta             BIGINT  NOT NULL,
    q15                     BIGINT  NULL,
    q16                     BIGINT  NULL,
    q17                     BIGINT  NULL,
    q18                     BIGINT  NULL,
    q19                     BIGINT  NULL,
    q20                     BIGINT  NULL,
    q25                     BIGINT  NULL,
    q26                     BIGINT  NULL,
    q27                     BIGINT  NULL,
    q28                     BIGINT  NULL,
    q29                     BIGINT  NULL,
    q30                     BIGINT  NULL,
    q31                     BIGINT  NULL,
    R301A                   TINYINT NULL,
    R301B                   TINYINT NULL,
    R301C                   TINYINT NULL,
    R301D                   TINYINT NULL,
    R301E                   TINYINT NULL,
    R301F                   TINYINT NULL,
    R301G                   TINYINT NULL,
    R301H                   TINYINT NULL,
    R301I                   TINYINT NULL,
    R301J                   TINYINT NULL,
    R301K                   TINYINT NULL,
    R301L                   TINYINT NULL,
    R302A                   TINYINT NULL,
    R302B                   TINYINT NULL,
    R302C                   TINYINT NULL,
    R302D                   TINYINT NULL,
    R302E                   TINYINT NULL,
    R302F                   TINYINT NULL,
    R302G                   TINYINT NULL,
    R302H                   TINYINT NULL,
    R302I                   TINYINT NULL,
    R302J                   TINYINT NULL,
    R302K                   TINYINT NULL,
    R302L                   TINYINT NULL,
    R302M                   TINYINT NULL
);
