CREATE TABLE neonato
(
    id_neonato           BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome_mae             VARCHAR(255),
    prontuario           VARCHAR(255),
    data_nascimento      DATE,
    data_internacao      DATE,
    data_desfecho        DATE,
    obito                TINYINT,
    apgar_1              BIGINT,
    apgar_5              BIGINT,
    peso_gramas          BIGINT,
    id_sexo              BIGINT,
    id_peso_nascimento   BIGINT,
    id_motivo_internacao BIGINT,
    id_local_nascimento  BIGINT,
    id_idade_gestacional BIGINT,
    id_tipo_parto        BIGINT,
    id_rotura_membrana   BIGINT,
    id_causa_obito       BIGINT,
    risco_infeccioso     TINYINT,
    sepse_clinica        TINYINT,
    criado_em            DATETIME,
    criado_por_id        BIGINT,
    alterado_em          DATETIME,
    alterado_por_id      BIGINT,
    is_active            TINYINT DEFAULT 1
);
