name: Deploy JAR UTI Neonatal (Local via Docker)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy-local:
    name: Deploy via Docker Compose (servidor local)
    runs-on: [ self-hosted, linux ]  # usa o runner que você configurou no outro servidor

    steps:
      # --------------------------------------------------
      # 1) Checkout do repositório
      # --------------------------------------------------
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # --------------------------------------------------
      # 2) Configura JDK 17
      # --------------------------------------------------
      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # --------------------------------------------------
      # 3) (Opcional) Configura Node.js
      # --------------------------------------------------
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.1.0'

      # --------------------------------------------------
      # 4) Cache das dependências do Gradle
      # --------------------------------------------------
      - name: Cache de dependências Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('*/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # --------------------------------------------------
      # 5) Cache de módulos npm
      # --------------------------------------------------
      - name: Cache de módulos npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # --------------------------------------------------
      # 6) Permissão no gradlew
      # --------------------------------------------------
      - name: Dar permissão ao gradlew
        run: chmod +x gradlew

      # --------------------------------------------------
      # 7) Build do Gradle (gera JAR em build/libs/)
      # --------------------------------------------------
      - name: Build com Gradle
        run: ./gradlew buildWithFrontend

      # --------------------------------------------------
      # 8) (Opcional) Upload do JAR como artifact
      # --------------------------------------------------
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/libs/*.jar

      # --------------------------------------------------
      # 9) Copiar o JAR para /var/www/neonatalepidemiology/app.jar
      # --------------------------------------------------
      - name: Copiar JAR para pasta Docker (local)
        run: |
          # Como o runner já está na raiz do repo:
          cp -f build/libs/pesquisa_uti_neonatal-0.0.1-SNAPSHOT.jar /var/www/neonatalepidemiology/app.jar

      # --------------------------------------------------
      # 10) Deploy via Docker Compose no servidor local
      # --------------------------------------------------
      - name: Parar e remover container antigo (se existir)
        run: |
          docker rm -f neonatalepidemiology_app || true

      - name: Deploy via Docker Compose (local)
        run: |
          cd /var/www
          docker compose build app
          docker compose up -d