name: Build and Deploy Neonatal Epidemiology

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Garantir permissão no gradlew
        run: chmod +x ./gradlew

      - name: Build do projeto (gera o JAR)
        run: ./gradlew buildWithFrontend

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build da imagem Docker
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          docker build -t $IMAGE_NAME:latest .

      - name: Push da imagem Docker
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          docker push $IMAGE_NAME:latest

  pull-on-server:
    name: Pull da nova imagem (servidor local)
    runs-on: self-hosted
    needs: build-and-push-image

    steps:
      - name: Atualizar imagem do app no servidor
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest
